export const env = {
  USER_SERVICE: process.env.NEXT_PUBLIC_USER_SERVICE_URL!,
  JOB_SERVICE: process.env.NEXT_PUBLIC_JOB_SERVICE_URL!,
  ACADEMIC_CONFIG_SERVICE: process.env.NEXT_PUBLIC_ACADEMIC_SERVICE_URL!,
  MESSAGE_SERVICE: process.env.NEXT_PUBLIC_MESSAGE_SERVICE_URL!,
};
